### PR TITLE
Feature/implement invite collaorators

### PR DESCRIPTION
**Pull request by sreejinsreenivasan**

### CODE REVIEW

**Review by vijin-govind — COMMENTED** [review]
Add collaborator, QA pass
but after invitation, the success modal is not close automatic

**Review by vijin-govind — COMMENTED** [review]
not reflecting the POW invitation in the author guy profile (not showing Collab POW)

**Comment by sreejinsreenivasan** [comment]
> not reflecting the POW invitation in the author guy profile (not showing Collab POW)

updated

**Review by vijin-govind — APPROVED** [review]
QA Pass
Invitation working ✅
collaboration reflecting on profile ✅

**Pull request merged**
